# A generic, single database configuration.

[alembic]
# path to migration script directory
script_location = app/infrastructure/database/migrations

# template used to generate migration file names; The default is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters which will be used to generate the
# slug field in migration file names
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be detected as revisions
# sourceless = false

# version location specification; This defaults
# to script_location/versions. When multiple version
# directories are required, use a space or newline separated list
# version_locations = %(here)s/bar %(here)s/bat script_location/versions

# set to 'true' to search source_path recursively for
# version files.
# recursive_version_locations = false

# output encoding used when --template is supplied
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://charityai_user:charityai_pass_2026@localhost:5432/charityai


[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root,alembic,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
