"""Initial PostgreSQL schema

Revision ID: a5fd6be10607
Revises: None
Create Date: 2026-08-06 23:25:01.901354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5fd6be10607'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rollout_percentage', sa.Float(), nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('key', name=op.f('uq_feature_flags_key'))
    )
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_alerts'))
    )
    op.create_index(op.f('ix_fraud_alerts_entity_id'), 'fraud_alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_id'), 'fraud_alerts', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('org_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('fcra_number', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('gallery_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sdg_goals', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('kyc_completed', sa.Boolean(), nullable=False),
    sa.Column('total_received', sa.Float(), nullable=False),
    sa.Column('total_beneficiaries', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=30), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('accepts_online_donations', sa.Boolean(), nullable=False),
    sa.Column('accepts_goods_donations', sa.Boolean(), nullable=False),
    sa.Column('tax_exemption_available', sa.Boolean(), nullable=False),
    sa.Column('tax_exemption_section', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('registration_number', name='uq_org_registration_number'),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index('ix_org_country', 'organizations', ['country'], unique=False)
    op.create_index('ix_org_status', 'organizations', ['status'], unique=False)
    op.create_index('ix_org_type', 'organizations', ['org_type'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_system_settings_key'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=72), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('oauth_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_status', sa.String(length=30), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('identity_verified', sa.String(length=20), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], name=op.f('fk_users_referred_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('phone', name='uq_users_phone'),
    sa.UniqueConstraint('referral_code', name=op.f('uq_users_referral_code'))
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['account_status'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_recommendations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('blood_donations',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('last_donation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_eligible_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('health_screening_passed', sa.Boolean(), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_blood_donations_donor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_donations'))
    )
    op.create_index('ix_blood_city', 'blood_donations', ['city'], unique=False)
    op.create_index(op.f('ix_blood_donations_id'), 'blood_donations', ['id'], unique=False)
    op.create_index(op.f('ix_blood_donations_is_deleted'), 'blood_donations', ['is_deleted'], unique=False)
    op.create_index('ix_blood_donor_id', 'blood_donations', ['donor_id'], unique=False)
    op.create_index('ix_blood_group', 'blood_donations', ['blood_group'], unique=False)
    op.create_table('campaigns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('goal_amount', sa.Float(), nullable=True),
    sa.Column('raised_amount', sa.Float(), nullable=False),
    sa.Column('donors_count', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('gallery_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('beneficiaries_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_campaigns_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('slug', name=op.f('uq_campaigns_slug'))
    )
    op.create_index('ix_campaigns_ends_at', 'campaigns', ['ends_at'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_is_deleted'), 'campaigns', ['is_deleted'], unique=False)
    op.create_index('ix_campaigns_org_id', 'campaigns', ['organization_id'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_index('ix_campaigns_type', 'campaigns', ['campaign_type'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notif_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notif_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notif_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('organization_documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_documents'))
    )
    op.create_index(op.f('ix_organization_documents_id'), 'organization_documents', ['id'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_type', sa.String(length=30), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_verifications'))
    )
    op.create_index('ix_otp_user_id_type', 'otp_verifications', ['user_id', 'otp_type'], unique=False)
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_table('receiver_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('income_category', sa.String(length=30), nullable=True),
    sa.Column('housing_status', sa.String(length=50), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('special_needs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('assigned_ngo_id', sa.UUID(), nullable=True),
    sa.Column('case_worker_id', sa.UUID(), nullable=True),
    sa.Column('ai_priority_score', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_documents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_ngo_id'], ['organizations.id'], name=op.f('fk_receiver_profiles_assigned_ngo_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_worker_id'], ['users.id'], name=op.f('fk_receiver_profiles_case_worker_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_receiver_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receiver_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_receiver_profiles_user_id'))
    )
    op.create_index(op.f('ix_receiver_profiles_id'), 'receiver_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_receiver_profiles_is_deleted'), 'receiver_profiles', ['is_deleted'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti'))
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index('ix_refresh_tokens_jti', 'refresh_tokens', ['jti'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('ocr_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_documents'))
    )
    op.create_index(op.f('ix_user_documents_id'), 'user_documents', ['id'], unique=False)
    op.create_index(op.f('ix_user_documents_is_deleted'), 'user_documents', ['is_deleted'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('total_donations_count', sa.Integer(), nullable=False),
    sa.Column('total_donation_amount', sa.Float(), nullable=False),
    sa.Column('volunteer_hours', sa.Float(), nullable=False),
    sa.Column('badges', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('session_token', name=op.f('uq_user_sessions_session_token'))
    )
    op.create_index('ix_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('volunteers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_tasks_per_week', sa.Integer(), nullable=False),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('badges', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('background_check_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['organizations.id'], name=op.f('fk_volunteers_ngo_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_volunteers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_volunteers_user_id'))
    )
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_index(op.f('ix_volunteers_is_deleted'), 'volunteers', ['is_deleted'], unique=False)
    op.create_table('campaign_milestones',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_milestones_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_milestones'))
    )
    op.create_index(op.f('ix_campaign_milestones_id'), 'campaign_milestones', ['id'], unique=False)
    op.create_table('donations',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('volunteer_id', sa.UUID(), nullable=True),
    sa.Column('donation_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('donation_method', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_tax_exempt', sa.Boolean(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('scheduled_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_window_start', sa.String(length=10), nullable=True),
    sa.Column('scheduled_window_end', sa.String(length=10), nullable=True),
    sa.Column('actual_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code', sa.String(length=200), nullable=True),
    sa.Column('qr_verified', sa.Boolean(), nullable=False),
    sa.Column('qr_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ngo_verified', sa.Boolean(), nullable=False),
    sa.Column('ngo_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ngo_verified_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('ai_fraud_score', sa.Float(), nullable=True),
    sa.Column('ai_fraud_flags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('ai_recommended_ngo', sa.String(length=36), nullable=True),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('impact_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_donations_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_donations_donor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ngo_id'], ['organizations.id'], name=op.f('fk_donations_ngo_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], name=op.f('fk_donations_volunteer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations')),
    sa.UniqueConstraint('tracking_number', name=op.f('uq_donations_tracking_number'))
    )
    op.create_index('ix_donations_campaign_id', 'donations', ['campaign_id'], unique=False)
    op.create_index('ix_donations_created_at', 'donations', ['created_at'], unique=False)
    op.create_index('ix_donations_donor_id', 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_is_deleted'), 'donations', ['is_deleted'], unique=False)
    op.create_index('ix_donations_ngo_id', 'donations', ['ngo_id'], unique=False)
    op.create_index('ix_donations_status', 'donations', ['status'], unique=False)
    op.create_index('ix_donations_type', 'donations', ['donation_type'], unique=False)
    op.create_table('volunteer_certificates',
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('certificate_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('verification_code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('fk_volunteer_certificates_volunteer_id_volunteers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_certificates')),
    sa.UniqueConstraint('verification_code', name=op.f('uq_volunteer_certificates_verification_code'))
    )
    op.create_index(op.f('ix_volunteer_certificates_id'), 'volunteer_certificates', ['id'], unique=False)
    op.create_table('donation_items',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ai_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name=op.f('fk_donation_items_donation_id_donations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_items'))
    )
    op.create_index(op.f('ix_donation_items_id'), 'donation_items', ['id'], unique=False)
    op.create_table('donation_pickups',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('route_optimized', sa.Boolean(), nullable=False),
    sa.Column('estimated_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_mins', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('qr_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name=op.f('fk_donation_pickups_donation_id_donations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], name=op.f('fk_donation_pickups_volunteer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_pickups'))
    )
    op.create_index(op.f('ix_donation_pickups_id'), 'donation_pickups', ['id'], unique=False)
    op.create_table('donation_receipts',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('sent_email', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name=op.f('fk_donation_receipts_donation_id_donations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_receipts')),
    sa.UniqueConstraint('receipt_number', name=op.f('uq_donation_receipts_receipt_number'))
    )
    op.create_index(op.f('ix_donation_receipts_id'), 'donation_receipts', ['id'], unique=False)
    op.create_table('donation_status_history',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name=op.f('fk_donation_status_history_donation_id_donations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_status_history'))
    )
    op.create_index(op.f('ix_donation_status_history_id'), 'donation_status_history', ['id'], unique=False)
    op.create_table('help_requests',
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('need_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('quantity_needed', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supporting_documents', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_priority_score', sa.Float(), nullable=True),
    sa.Column('ai_verified', sa.Boolean(), nullable=False),
    sa.Column('matched_donation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['matched_donation_id'], ['donations.id'], name=op.f('fk_help_requests_matched_donation_id_donations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['receiver_profiles.id'], name=op.f('fk_help_requests_receiver_id_receiver_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_requests'))
    )
    op.create_index('ix_help_req_receiver_id', 'help_requests', ['receiver_id'], unique=False)
    op.create_index('ix_help_req_status', 'help_requests', ['status'], unique=False)
    op.create_index('ix_help_req_type', 'help_requests', ['need_type'], unique=False)
    op.create_index(op.f('ix_help_requests_id'), 'help_requests', ['id'], unique=False)
    op.create_index(op.f('ix_help_requests_is_deleted'), 'help_requests', ['is_deleted'], unique=False)
    op.create_table('transactions',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('gateway_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_signature', sa.String(length=500), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_transactions_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name=op.f('fk_transactions_donation_id_donations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_transactions_donor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_gateway_order_id'), 'transactions', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_gateway_payment_id'), 'transactions', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_is_deleted'), 'transactions', ['is_deleted'], unique=False)
    op.create_index('ix_txn_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_txn_donation_id', 'transactions', ['donation_id'], unique=False)
    op.create_index('ix_txn_donor_id', 'transactions', ['donor_id'], unique=False)
    op.create_index('ix_txn_gateway', 'transactions', ['gateway'], unique=False)
    op.create_index('ix_txn_status', 'transactions', ['status'], unique=False)
    op.create_table('volunteer_tasks',
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pickup_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('drop_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('qr_check_in_code', sa.String(length=100), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('volunteer_notes', sa.Text(), nullable=True),
    sa.Column('ngo_rating', sa.Integer(), nullable=True),
    sa.Column('ngo_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], name=op.f('fk_volunteer_tasks_donation_id_donations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('fk_volunteer_tasks_volunteer_id_volunteers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_tasks'))
    )
    op.create_index('ix_vol_task_status', 'volunteer_tasks', ['status'], unique=False)
    op.create_index('ix_vol_task_volunteer_id', 'volunteer_tasks', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_tasks_id'), 'volunteer_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_tasks_is_deleted'), 'volunteer_tasks', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_tasks_is_deleted'), table_name='volunteer_tasks')
    op.drop_index(op.f('ix_volunteer_tasks_id'), table_name='volunteer_tasks')
    op.drop_index('ix_vol_task_volunteer_id', table_name='volunteer_tasks')
    op.drop_index('ix_vol_task_status', table_name='volunteer_tasks')
    op.drop_table('volunteer_tasks')
    op.drop_index('ix_txn_status', table_name='transactions')
    op.drop_index('ix_txn_gateway', table_name='transactions')
    op.drop_index('ix_txn_donor_id', table_name='transactions')
    op.drop_index('ix_txn_donation_id', table_name='transactions')
    op.drop_index('ix_txn_created_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_deleted'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_order_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_help_requests_is_deleted'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_id'), table_name='help_requests')
    op.drop_index('ix_help_req_type', table_name='help_requests')
    op.drop_index('ix_help_req_status', table_name='help_requests')
    op.drop_index('ix_help_req_receiver_id', table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index(op.f('ix_donation_status_history_id'), table_name='donation_status_history')
    op.drop_table('donation_status_history')
    op.drop_index(op.f('ix_donation_receipts_id'), table_name='donation_receipts')
    op.drop_table('donation_receipts')
    op.drop_index(op.f('ix_donation_pickups_id'), table_name='donation_pickups')
    op.drop_table('donation_pickups')
    op.drop_index(op.f('ix_donation_items_id'), table_name='donation_items')
    op.drop_table('donation_items')
    op.drop_index(op.f('ix_volunteer_certificates_id'), table_name='volunteer_certificates')
    op.drop_table('volunteer_certificates')
    op.drop_index('ix_donations_type', table_name='donations')
    op.drop_index('ix_donations_status', table_name='donations')
    op.drop_index('ix_donations_ngo_id', table_name='donations')
    op.drop_index(op.f('ix_donations_is_deleted'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index('ix_donations_donor_id', table_name='donations')
    op.drop_index('ix_donations_created_at', table_name='donations')
    op.drop_index('ix_donations_campaign_id', table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_campaign_milestones_id'), table_name='campaign_milestones')
    op.drop_table('campaign_milestones')
    op.drop_index(op.f('ix_volunteers_is_deleted'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('ix_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_documents_is_deleted'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_id'), table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_jti', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_receiver_profiles_is_deleted'), table_name='receiver_profiles')
    op.drop_index(op.f('ix_receiver_profiles_id'), table_name='receiver_profiles')
    op.drop_table('receiver_profiles')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_index('ix_otp_user_id_type', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_documents_id'), table_name='organization_documents')
    op.drop_table('organization_documents')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notif_user_id', table_name='notifications')
    op.drop_index('ix_notif_read', table_name='notifications')
    op.drop_index('ix_notif_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_campaigns_type', table_name='campaigns')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index('ix_campaigns_org_id', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_deleted'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_ends_at', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_blood_group', table_name='blood_donations')
    op.drop_index('ix_blood_donor_id', table_name='blood_donations')
    op.drop_index(op.f('ix_blood_donations_is_deleted'), table_name='blood_donations')
    op.drop_index(op.f('ix_blood_donations_id'), table_name='blood_donations')
    op.drop_index('ix_blood_city', table_name='blood_donations')
    op.drop_table('blood_donations')
    op.drop_index('ix_audit_user_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index('ix_org_type', table_name='organizations')
    op.drop_index('ix_org_status', table_name='organizations')
    op.drop_index('ix_org_country', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_fraud_alerts_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_entity_id'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
